### ISSUE TITLE
客户端加密消息了，服务器端没有解密消息的操作，还有很难点开发送消息的窗口

### ISSUE THREAD

**Issue by wanjundegithub** [kingston-csj/im#13]

**Comment by kingston-csj** [comment]
> _No description provided._

服务端直接验证的是密文，所以没有解密。打开发送消息窗口的方式是选中好友，然后快速双击就可以

**Comment by kingston-csj** [comment]
> _No description provided._

服务端直接验证的是密文，所以没有解密。打开发送消息窗口的方式是选中好友，然后快速双击就可以

**Comment by kingston-csj** [comment]
测试的数据库备份数据是旧的，更新下测试数据即可。

**Comment by wanjundegithub** [comment]
好的，谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月20日(周二) 下午4:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kingston-csj/im] 客户端加密消息了，服务器端没有解密消息的操作，还有很难点开发送消息的窗口 (#13)




 
测试的数据库备份数据是旧的，更新下测试数据即可。
