### ISSUE TITLE
默认账户无法登录但自己注册的可以登录，数据库写入的信息也有问题

### ISSUE THREAD

**Issue by Rain-ziyu** [kingston-csj/im#14]
客户端发送给服务端的密码是加密的但服务端未对密码进行解密
![image](https://user-images.githubusercontent.com/70049441/115197865-0d5c9d00-a124-11eb-8b95-a63b44cb5b9b.png)

**Comment by kingston-csj** [comment]
> 客户端发送给服务端的密码是加密的但服务端未对密码进行解密
> ![image](https://user-images.githubusercontent.com/70049441/115197865-0d5c9d00-a124-11eb-8b95-a63b44cb5b9b.png)

测试sql没有同步上传。可以了。

**Comment by kingston-csj** [comment]
当初脑子进水了，选了个冷门ui库。文档奇缺，确实不太想维护。后续新加web客户端介入，变成桌面应用，web应用双端，也不是不可以。
