### ISSUE TITLE
退出登录，ChannelUtils没有清除对应的IoSession

### ISSUE THREAD

**Issue by xgzcx623** [kingston-csj/im#16]
退出登录，ChannelUtils没有清除对应的IoSession，如下只有添加：

	/**
	 * 添加新的会话
	 * @param channel
	 * @param session
	 * @return
	 */
	public static boolean addChannelSession(Channel channel, IoSession session) {
		Attribute<IoSession> sessionAttr = channel.attr(SESSION_KEY);
		return sessionAttr.compareAndSet(null, session);
	}

退出时，是否应该  sessionAttr.set(null)  ?

**Comment by kingston-csj** [comment]
已重构，这段代码已经去掉了。
