### ISSUE TITLE
表情那一块 客户端minio文件服务器上的表情图片一直下载不下来 报403错误 

### ISSUE THREAD

**Issue by lzf19961231** [kingston-csj/im#27]
我自己改动了一下这样是不是有什么地方设置错了 大佬
![1733127795154](https://github.com/user-attachments/assets/c80b3fb9-df3f-4a2d-a80d-d960801257a9)
![1733127817024](https://github.com/user-attachments/assets/544c7aab-e479-4990-b939-8eef37c1bacd)
![1733127833864](https://github.com/user-attachments/assets/ef3e82e4-2736-400a-90ce-35fcafaafd33)
![1733127863770](https://github.com/user-attachments/assets/ba1c1899-1fc0-458d-9c3a-e4301dc449cd)
文件服务器上有 但是按照/emoji/list这个路径访问有问题 一直报403错误 我用mc客户端开放了下载权限了 但是还是一样

**Comment by kingston-csj** [comment]
为什么你的访问路径是 127.0.0.1:9000/emoli/list。
这里为什么是list，而不是具体的某一个表情id呢？
如果确定文件服务器有这个资源emoli/list，可以设置下minio的访问权限，参数《https://jforgame.blog.csdn.net/article/details/136687773》我这篇文章。

**Comment by lzf19961231** [comment]
> 为什么你的访问路径是 127.0.0.1:9000/emoli/list。 这里为什么是list，而不是具体的某一个表情id呢？ 如果确定文件服务器有这个资源emoli/list，可以设置下minio的访问权限，参数《[https://jforgame.blog.csdn.net/article/details/136687773》我这篇文章。](https://jforgame.blog.csdn.net/article/details/136687773%E3%80%8B%E6%88%91%E8%BF%99%E7%AF%87%E6%96%87%E7%AB%A0%E3%80%82)

因为在这里您登录的时候有个从minio加载表情的代码逻辑
![1734574607706](https://github.com/user-attachments/assets/6dcb89c2-271e-4b3d-b05a-6070910799ba)
而我改动了那个RemoteHttpUrl配置项的值为自己本地，但是按照RemoteHttpUrl+/emoji/list 拼接出来的url访问就变成问题描述的那样 所以我有点遗憾哪个环节出了问题 您那篇文章404了

**Comment by lzf19961231** [comment]
> 客户端加载表情包的url不是minio的文件路径啊，那是服务器的接口路径 ![image](https://private-user-images.githubusercontent.com/19730460/397703308-e4ff98fa-fc3b-4b75-8e5d-1c26f607ce89.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ3OTAzNTAsIm5iZiI6MTczNDc5MDA1MCwicGF0aCI6Ii8xOTczMDQ2MC8zOTc3MDMzMDgtZTRmZjk4ZmEtZmMzYi00Yjc1LThlNWQtMWMyNmY2MDdjZTg5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIxVDE0MDczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1ZWE1MDI2Y2NkOTM2MWViYTEwMjM1NGVmMzY4NjFmNzY4OWRkZGNhMjE5MWM2OWRhMDQ1MGQ2ZjBlZTczODYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NDVv0GpZ9kRk-bDbmIC7q0CaWmxbaUYysZUgGrmZTxY)
可以了 大佬 是我之前没有开放minio bucket访问权限的锅
