### ISSUE TITLE
chat_room.sql应该是过时的

### ISSUE THREAD

**Issue by hyz123456789** [kingston-csj/im#3]
chat_room.sql应该是过时的

**Comment by hyz123456789** [comment]
感谢您的回复，是项目中有两份SQL文件，我一开始导入的一份是过期的，在config目录下，不能使用，建议删掉。后面我导入另一份是可以完美运行的。

**Comment by kingston-csj** [comment]
多谢提醒，已同步更新两个配置文件。并自测可以运行
