### ISSUE TITLE
服务端不能运行

### ISSUE THREAD

**Issue by liwei23333** [kingston-csj/im#6]
Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
错误提示是这样的  可以加qq交流一下吗  谢谢  qq1394095671

**Comment by kingston-csj** [comment]
你更新下代码试试。如果还有问题，用maven的命令行mvn dependency:tree
看下那个jar包依赖这个jaxb，我本地环境没有重现
